/**
 * Typed access to the Vite environment variables.
 *
 * Vite only exposes variables prefixed with `VITE_`. Everything here is public
 * (it ends up in the client bundle), so no secrets belong in `.env`.
 */

const rawBaseUrl = import.meta.env.VITE_API_BASE_URL as string | undefined;

/**
 * Base URL used by every API call.
 * Defaults to the relative path `/api/v1`, which the Vite dev proxy forwards to
 * the Laravel API (so requests are same-origin and CORS never applies).
 */
export const API_BASE_URL: string =
  rawBaseUrl && rawBaseUrl.trim().length > 0 ? rawBaseUrl.trim() : "/api/v1";

const rawDemoStudentId = Number(import.meta.env.VITE_DEMO_STUDENT_ID);

/**
 * Student profile id used by the student portal.
 * See `docs/LIMITATIONS.md` (workaround W2) - the API has no "my profile" endpoint.
 */
export const DEMO_STUDENT_ID: number =
  Number.isInteger(rawDemoStudentId) && rawDemoStudentId > 0 ? rawDemoStudentId : 1;

/** Request timeout in milliseconds. */
export const API_REQUEST_TIMEOUT_MS = 20_000;

/** Human readable application name, used in the shell and page titles. */
export const APP_NAME = "Student Information Management";

/** Interactive API documentation generated by the backend (Scramble). */
export const API_DOCS_URL = "http://127.0.0.1:8000/api/docs";
